- name: Set up SSH key
  run: |
    mkdir -p ~/.ssh
    echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
    chmod 600 ~/.ssh/id_rsa
    ssh-keyscan 52.86.72.158 >> ~/.ssh/known_hosts

- name: Execute deployment script via SSH
  run: ssh -i ~/.ssh/id_rsa inhouse@52.86.72.158 'bash -s' < ./home/inhouse/start.sh
