name: Deploy to GCP VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.GCP_SSH_KEY }}

   - name: Execute remote command
      run: ssh -o StrictHostKeyChecking=no inhouse@52.86.72.158 "bash -s" < /home/inhouse/start.sh

