name: Deploy to GCP VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.GCP_SSH_KEY }}

    - name: Copy files to GCP server
      run: scp -o StrictHostKeyChecking=no -r ./ inhouse@52.86.72.158:/home/inhouse/my_app

